### ISSUE TITLE
Fix author list Checklist

### ISSUE THREAD

**Issue by anna-parker** [pathoplexus/pathoplexus#110]
- [x] Write script: https://github.com/loculus-project/loculus/pull/2653#issuecomment-2321430999
- [x] Test locally with actual v1 and v2s due to sort author order
- [in process] Staging will get the new loculus version:
- [x] create PR in pathoplexus/pathoplexus: https://github.com/pathoplexus/pathoplexus/pull/64
- [ ] Run the script on staging
- [ ] Verify staging is good
- [ ] create production db clone within RDS instance (for swifter recovery in case something happens)
- [ ] production gets new  loculus version
- [ ] run script on production
- [ ] verify production is good
